// Code generaTed by fileb0x at "2023-08-17 14:50:10.838343 +0800 CST m=+0.000586209" from config file "b0x.yaml" DO NOT EDIT.
// modified(2023-08-17 14:46:37.942104207 +0800 CST)
// original path: source/mysql.sql.tpl

package template

import (
	"os"
)

// FileMysqlSQLTpl is "/mysql.sql.tpl"
var FileMysqlSQLTpl = []byte("")

func init() {

	f, err := FS.OpenFile(CTX, "/mysql.sql.tpl", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileMysqlSQLTpl)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
