// Code generaTed by fileb0x at "2023-08-17 14:50:10.838796 +0800 CST m=+0.001039084" from config file "b0x.yaml" DO NOT EDIT.
// modified(2023-08-17 14:46:44.844081224 +0800 CST)
// original path: source/clickhouse.sql.tpl

package template

import (
	"os"
)

// FileClickhouseSQLTpl is "/clickhouse.sql.tpl"
var FileClickhouseSQLTpl = []byte("")

func init() {

	f, err := FS.OpenFile(CTX, "/clickhouse.sql.tpl", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileClickhouseSQLTpl)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
